package generator;

import dto.ColumnMetadata;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.IOException;
import java.util.LinkedList;
import java.util.Map;

@Slf4j
public class FileGenerator {
    public Map<String, LinkedList<ColumnMetadata>> metadata;

    public FileGenerator(Map<String, LinkedList<ColumnMetadata>> metadata) {
        this.metadata = metadata;
    }

    public void generateRESTWebServicesFiles() {
        generateConfig();
        generateDto();
        generateService();
        generateController();
    }

    public void generateConfig() {
        createProjectFile("config\\", "DbCon.java");
    }

    public void generateController() {
        metadata.forEach((t, k) -> {
            createProjectFile("controller\\", capitalizeFirstLetter(t) + "Controller" + ".java");
        });
    }

    public void generateDto() {
        metadata.forEach((t, k) -> {
            createProjectFile("dto\\", capitalizeFirstLetter(t) + ".java");
        });
    }

    public void generateService() {
        metadata.forEach((t, k) -> {
            createProjectFile("service\\impl\\", capitalizeFirstLetter(t) + "Service" + ".java");
        });
        createProjectFile("service\\", "ServiceTemplate.java");
    }

    private void createProjectFile(String path, String fileName) {
        try {
            String absolutePath = System.getProperty("user.dir") + "\\src\\main\\java\\autogenerated\\" + path;
            var file = new File(absolutePath + fileName);
            if (file.createNewFile())
                log.info("In directory " + absolutePath + " file " + file.getName() + " has been created");
        } catch (IOException e) {
            log.error(e.getMessage());
            e.printStackTrace();
        }
    }

    private String capitalizeFirstLetter(String str)
    {
        return str.substring(0, 1).toUpperCase() + str.substring(1).toLowerCase();
    }
}
