package generator.content;

import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;
import config.Common;
import config.Package;
import dto.DbParameters;
import lombok.extern.slf4j.Slf4j;

import javax.lang.model.element.Modifier;
import java.sql.Connection;
import java.sql.DriverManager;

@Slf4j
public class ConfigGenerator {
    public void generateConfig(DbParameters dbP) {
        Common.writeToJavaFile(Package.AUTOGENERATED_CONFIG, TypeSpec
                .classBuilder("DbCon")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Slf4j.class)
                .addMethod(generateMethod(dbP))
                .build());
    }

    private MethodSpec generateMethod(DbParameters dbP) {
        return MethodSpec
                .methodBuilder("connection")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(Connection.class)
                .beginControlFlow("try")
                .addStatement("Class.forName($S)", dbP.getDriver())
                .addStatement("return $T.getConnection($S, $S, $S)", DriverManager.class, dbP.getUrl(), dbP.getUser(), dbP.getPassword())
                .nextControlFlow("catch ($T e)", Exception.class)
                .addStatement("log.error(e.getMessage())")
                .addStatement("throw new $T()", RuntimeException.class)
                .endControlFlow()
                .build();
    }
}
