package generator.content;

import config.Path;
import lombok.extern.slf4j.Slf4j;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

@Slf4j
public class ServiceGenerator {

    public void generateService() {

    }

    public void generateServiceImpl() {

    }

    public void generateServiceTemplate() {
        String serviceTemplateContent = "package autogenerated.service;\n" +
                "\n" +
                "import java.util.List;\n" +
                "\n" +
                "public interface ServiceTemplate<T> {\n" +
                "    List<T> get();\n" +
                "    T get(int id);\n" +
                "    void add(T t);\n" +
                "    void delete(int id);\n" +
                "    void update(int id);\n" +
                "}";
        writeToFile(Path.AUTOGENERATED_SERVICE, "ServiceTemplate.java", serviceTemplateContent);
    }

    public void writeToFile(String path, String fileName, String content) {
        try (var bufferedWriter = new BufferedWriter(new FileWriter(path + fileName))) {
            bufferedWriter.write(content);
        } catch (IOException e) {
            log.error(e.getMessage());
            throw new RuntimeException();
        }
    }

}
