package config;

import lombok.extern.slf4j.Slf4j;
import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.IOException;

@Slf4j
public class DirectoryCreator {

    public void generateRESTWebServicesStructure() {
        createProjectDirectory(Path.AUTOGENERATED);
        createProjectDirectory(Path.AUTOGENERATED_CONFIG);
        createProjectDirectory(Path.AUTOGENERATED_CONTROLLER);
        createProjectDirectory(Path.AUTOGENERATED_DTO);
        createProjectDirectory(Path.AUTOGENERATED_SERVICE);
        createProjectDirectory(Path.AUTOGENERATED_SERVICE_IMPL);
    }

    private void createProjectDirectory(String path) {
        try {
            FileUtils.forceMkdir(new File(path));
        } catch (IOException e) {
            log.error(e.getMessage());
            throw new RuntimeException();
        }
    }

}
