package config;

import lombok.extern.slf4j.Slf4j;
import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.IOException;

@Slf4j
public class DirectoryCreator {

    public void generateRESTWebServicesStructure() {
        createProjectDirectory("autogenerated");
        createProjectDirectory("autogenerated/config");
        createProjectDirectory("autogenerated/controller");
        createProjectDirectory("autogenerated/dto");
        createProjectDirectory("autogenerated/service");
        createProjectDirectory("autogenerated/service/impl");
    }

    private void createProjectDirectory(String path) {
        try {
            FileUtils.forceMkdir(new File(System.getProperty("user.dir") + "/src/main/java/" + path));
        } catch (IOException e) {
            log.error(e.getMessage());
            throw new RuntimeException();
        }
    }

}
