package config;

public class Package {
    private Package() {
    }

    public static final String AUTOGENERATED = "autogenerated";
    public static final String AUTOGENERATED_CONFIG = AUTOGENERATED + ".config";
    public static final String AUTOGENERATED_CONTROLLER = AUTOGENERATED + ".controller";
    public static final String AUTOGENERATED_DTO = AUTOGENERATED + ".dto";
    public static final String AUTOGENERATED_SERVICE = AUTOGENERATED + ".service";
    public static final String AUTOGENERATED_SERVICE_IMPL = AUTOGENERATED_SERVICE + ".impl";
}
