package config;

public class Package {
    private Package() {
    }

    public static final String AUTOGENERATED = "autogenerated";
    public static final String AUTOGENERATED_CONFIG = AUTOGENERATED + Constants.DOT + "config";
    public static final String AUTOGENERATED_CONTROLLER = AUTOGENERATED + Constants.DOT + "controller";
    public static final String AUTOGENERATED_DTO = AUTOGENERATED + Constants.DOT + "dto";
    public static final String AUTOGENERATED_SERVICE = AUTOGENERATED + Constants.DOT + "service";
    public static final String AUTOGENERATED_SERVICE_IMPL = AUTOGENERATED_SERVICE + Constants.DOT + "impl";
}
